app = "justinlam-familytree"
primary_region = "sin"

[build]

[env]
  PORT = "3000"
  NODE_ENV = "production"
  UPLOAD_DIR = "/data/uploads"

[[mounts]]
  source = "uploads"
  destination = "/data/uploads"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "35s"
    interval = "10s"
    timeout = "5s"
    method = "GET"
    path = "/"
